Controllers/ManageAccountController.cs
using AppForVaccine.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Twilio;
using Twilio.Rest.Api.V2010.Account;

namespace AppForVaccine.Controllers
{
    [Authorize]
    public class ManageAccountController : Controller
    {
        private const string Vaccinated = "חוסן";
        private const string Not_Vaccinated = "לא חוסן";
        private const string Age0To10 = "0 - 10";
        private ApplicationDbContext _db = new ApplicationDbContext();

        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ManageAccountController()
        {
        }

        public ManageAccountController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: ManageAccount
        [HttpGet]
        public ActionResult Index()
        {
            var countersContainer = new CountersContainer();
            countersContainer.Users = _db.Users.Count();
            countersContainer.Therapist = _db.Therapists.Count();
            countersContainer.Clinics = _db.CityLists.Count();
            countersContainer.vaccinations = _db.Vaccinations.Count();
            return View(countersContainer);
            //@Session["username"]
        }

        public ActionResult IndexOfTherapist()
        {
            var countersContainer1 = new CountersContainer1();
            countersContainer1.vaccinations = _db.Vaccinations.Count();
            //countersContainer1.Users = _db.patientvaccinations.where<Therapist==>.Count().;
            countersContainer1.Therapist = _db.Therapists.Count();
            countersContainer1.Clinics = _db.CityLists.Count();
            countersContainer1.Patients = _db.Patients.Count();
            return View(countersContainer1);
        }
        //[HttpPost]
        ////[ValidateAntiForgeryToken]
        //public ActionResult LogOff()
        //{
        //    AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
        //    return RedirectToAction("Login", "Account");
        //}
        
        [HttpGet]
        public ActionResult VaccineReminder(int? patientid)
        {
            DateTime filterD = DateTime.Now.AddDays(7); // Get patient that are due in 7 days a
            if (patientid != null)
            {
                var PatientData = _db.PatientVaccinations.Where(x => x.PatientId == patientid && x.Status == false && x.scheduledDate <= filterD && x.ReminderSent==false).ToList();
                var vReminderlist = new List<VaccinationReminderModel>();

                foreach (var item in PatientData)
                {
                    var vr = new VaccinationReminderModel()
                    {
                        VaccineName = item.VaccineName,
                        FirstName = item.FirstName,
                        LastName = item.LastName,
                        PatientId = item.PatientId,
                        Status = item.Status,
                        PatientNumber = item.PatientNumber,
                        PatientVaccinatedId = item.PatientVaccinatedId,
                        scheduledDate = item.scheduledDate.Value.ToString("MM/dd/yyyy")
                    };
                    vReminderlist.Add(vr);
                }
                return View(vReminderlist);
            }
            else
            {
                var PatientData = _db.PatientVaccinations.Where(x => x.Status == false && x.scheduledDate <= filterD && x.ReminderSent==false ).ToList();
                var vReminderlist = new List<VaccinationReminderModel>();

                foreach (var item in PatientData)
                {
                    var vr = new VaccinationReminderModel()
                    {
                        VaccineName = item.VaccineName,
                        FirstName = item.FirstName,
                        LastName = item.LastName,
                        PatientId = item.PatientId,
                        Status = item.Status,
                        PatientNumber = item.PatientNumber,
                        ReminderSent = item.ReminderSent.Value,
                        PatientVaccinatedId = item.PatientVaccinatedId,
                        scheduledDate = item.scheduledDate.Value.ToString("MM/dd/yyyy")
                    };
                    vReminderlist.Add(vr);
                }
                return View(vReminderlist);
            }
        }

        public void TaskReminder()
        {
            DateTime filterD = DateTime.Now.AddDays(7);
          
                var PatientData = _db.PatientVaccinations.Where(x => x.Status == false && x.scheduledDate <= filterD).ToList();
                var vReminderlist = new List<VaccinationReminderModel>();
                
                foreach (var item in PatientData)
                {
                    var vr = new VaccinationReminderModel()
                    {
                        VaccineName = item.VaccineName,
                        FirstName = item.FirstName,
                        LastName = item.LastName,
                        PatientId = item.PatientId,
                        Status = item.Status,
                        PatientVaccinatedId = item.PatientVaccinatedId,
                        scheduledDate = item.scheduledDate.Value.ToString("MM/dd/yyyy"),

                    };

                var phone = _db.Patients.Where(x => x.PatientId == item.PatientId).FirstOrDefault();


                var snd = new SmsEntity()
                    {
                    content = "Vaccine for " + item.VaccineName + "is due to take place",
                    Mobile = phone.Phone,
                        //sender = "",
                    };
                    SmsSenderPoint smsSenderPoint = new SmsSenderPoint();
                    smsSenderPoint.GetAPIReponse(snd);
               }    
        }

        
        public ActionResult GetPatient( string patientid)
        {
            //if (patientid !=null)
            //{
                var PatientData = _db.Patients.Where(x => x.PatientNumber == patientid).FirstOrDefault();
                return View(PatientData);
            //}
            //var patientd = _db.Patients.Where(x =>x.PatientId == 1).FirstOrDefault();
         
           // return View(patientd);
        }

        [HttpGet]
        public ActionResult GetVaccination(string patientid) 
        {
            //if (patientid != null)
            //{
                var PatientData = _db.PatientVaccinations.Where(x => x.PatientNumber == patientid).ToList();
                var vList = new List<PatientVaccinationModelList>();
                foreach (var item in PatientData)
                {

                    bool dat = false;
                    if (item.VaccinationDate == null) { dat = true; }
                    bool thera = false;
                    if (item.Therapist == null) { thera = true; }
                    //b = a != null ? a : b;
                    var nuser = new PatientVaccinationModelList()
                    {
                        PatientVaccinatedId = item.PatientVaccinatedId,
                        VaccineName = item.VaccineName,
                        Status = item.Status,
                        Therapist = thera ? null : item.Therapist,
                        VaccinatedDate = dat ? null : item.VaccinationDate.Value.ToString("MM/dd/yyyy"),
                        NextVaccineDate = item.NextVaccinaDate.Value.ToString("MM/dd/yyyy")
                    };
                    vList.Add(nuser);
                }
                if (PatientData.Count == 0)
                {
                var vaccinationModel1 = new PatientVaccination()
                {
                   
                    PatList = vList
                };
                return View(vaccinationModel1);
            }
                var vaccinationModel = new PatientVaccination()
                {
                    PatientNumber= PatientData.Select(x => x.PatientNumber).First(),
                    PatientId = PatientData.Select(x => x.PatientId).First(),
                    FirstName = PatientData.Select(x =>x.FirstName).First(),
                    LastName = PatientData.Select(x => x.LastName).First(),
                    UniqueId = PatientData.Select(x => x.UniqueId).First(),
                    PatList = vList
                };
                return View(vaccinationModel);
            //}
            //else
            //{
            //    var PatientData = _db.PatientVaccinations.Where(x => x.PatientId == 0).ToList();
            //    var vList = new List<PatientVaccinationModelList>();
            //    foreach (var item in PatientData)
            //    {
            //        bool dat = false;
            //        if (item.VaccinationDate == null) { dat = true;   }
            //        bool thera = false;
            //        if (item.Therapist == null) { thera = true; }
            //        //b = a != null ? a : b;
            //        var nuser = new PatientVaccinationModelList()
            //        {
            //            PatientVaccinatedId = item.PatientVaccinatedId,
            //            VaccineName = item.VaccineName,

Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Responsive Admin &amp; Dashboard Template based on Bootstrap 5">
    <meta name="author" content="AdminKit">
    <meta name="keywords" content="adminkit, bootstrap, bootstrap 5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">
    <title>@ViewBag.Title - Vaccine App</title>
    <link href="~/Content/CSS/bootstrap.css" rel="stylesheet" />
    <link href="~/Fontawesome/css/all.css" rel="stylesheet" />
    <link href="~/Content/CSS/app.css" rel="stylesheet" />
    @RenderSection("Head", false)
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
   
</head>

<body>


    <div class="w3-clear"></div>
    <div class="wrapper">
        @*Sidebar Navegation Start Here*@

        <nav id="sidebar" class="sidebar js-sidebar">
            <div class="sidebar-content js-simplebar">
                <a class="sidebar-brand" href="@Url.Action("Index", "ManageAccount")">
                    <span class="align-middle">מנהל מערכת </span>
                </a>

                <ul class="sidebar-nav">

                    <li class="sidebar-item active">
                        <a class="sidebar-link fs-4" href="@Url.Action("Index", "ManageAccount")">
                            <i class="fa-solid fa-gauge"></i><span class="align-middle">ראשי</span>
                        </a>
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link fs-4" href="@Url.Action("UserList", "ManageAccount")">
                            <i class="fa-regular fa-users"></i><span class="align-middle">משתמשים</span>
                        </a>
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link fs-4" href="@Url.Action("GetTherapist", "ManageAccount")">
                            <i class="fa-solid fa-user-doctor"></i><span class="align-middle">מטפלים</span>
                        </a>
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link fs-4" href="@Url.Action("VaccineReminder", "ManageAccount")">
                            <i class="fa-sharp fa-solid fa-business-time"></i><span class="align-middle">תזכורת</span>
                        </a>
                    </li>

                    @*<li class="sidebar-item">
                            <a class="sidebar-link fs-4" href="@Url.Action("GetVaccinationRecord", "ManageAccount")">
                                <i class="fa-light fa-person"></i><span class="align-middle">Vaccine Patient</span>
                            </a>
                        </li>*@

                    <li class="sidebar-item">
                        <a class="sidebar-link fs-4" href="@Url.Action("GetVaccine", "ManageAccount")">
                            <i class="fa-solid fa-syringe"></i><span class="align-middle">חיסונים</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link fs-4" href="@Url.Action("GetCity", "ManageAccount")">
                            <i class="fa-solid fa-hospital"></i><span class="align-middle">מרפאות</span>
                        </a>
                    </li>


                    <li class="nav-item dropdown">
                        <a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-bs-toggle="dropdown">
                            <i class="align-middle" data-feather="settings"></i>
                        </a>

                        <a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#" data-bs-toggle="dropdown">
                            &nbsp;&nbsp;&nbsp;<i class="fa-solid fa-file-chart-column fs-4" style="color: rgba(233,236,239,.5);"></i>&nbsp;&nbsp;&nbsp;<span class="fs-4" style="color: rgba(233,236,239,.5);">דוחות</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end">
                            <a class="dropdown-item fs-4" href="@Url.Action("Report", "ManageAccount")"><i class="fa-solid fa-arrow-trend-up"></i> צפייה בדוחות</a>
                            <a class="dropdown-item fs-4" href="@Url.Action("ReportDownload", "ManageAccount")"><i class="fa-solid fa-chart-user"></i> יצוא דוחות</a>
                            <div class="dropdown-divider"></div>

                        </div>

                      
                    <li class="sidebar-header border-top mt-2 fs-4 text-muted"></li>
                    


                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                    <li class="sidebar-item">
                        <a class="sidebar-link fs-4" href="@Url.Action("ChangePasswordAdmin", "ManageAccount")">
                            <i class="fa-solid fa-lock"></i><span class="align-middle">שינוי סיסמא</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link fs-4" href="https://localhost:44347/hangfire" target="_blank">
                            <i class="fa-solid fa-server"></i><span class="align-middle">מעקב תזכורות</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link fs-4" href="https://console.twilio.com/us1/monitor/logs/sms?frameUrl=%2Fconsole%2Fsms%2Flogs%3Fx-target-region%3Dus1&currentFrameUrl=%2Fconsole%2Fsms%2Flogs%3F__override_layout__%3Dembed%26bifrost%3Dtrue%26x-target-region%3Dus1" target="_blank">
                            <i class="fa-solid fa-messages"></i><span class="align-middle">מעקב הודעות</span>
                        </a>
                    </li>

                </ul>
            </div>
        </nav>

        <div class="main">
            <nav class="navbar navbar-expand navbar-light navbar-bg">

                <a class="sidebar-toggle js-sidebar-toggle">
                    <i class="hamburger align-self-center"></i>
                </a>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav navbar-align">
                        @*Top Navegation Start Here*@
                        <li class="nav-item dropdown">
                            <a class="nav-link d-none d-sm-inline-block fs-4" href="#" data-bs-toggle="dropdown">
                                <i class="fa-duotone fa-hands-clapping"></i>&nbsp;<span>שלום!&nbsp;@Session["username"]</span>
                            </a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link d-none d-sm-inline-block fs-4" href="/ManageAccount/AdminProfile/@Session["id"]">
                                <i class="fa-solid fa-user"></i>&nbsp;
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-none d-sm-inline-block fs-4" href="@Url.Action("LogOff", "Account")">
                                <i class="fa-regular fa-arrow-up-left-from-circle"></i>&nbsp;
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <img src="~/Image/Free_Sample_By_Wix (1).svg"style="height:45px; width:45px " />

                        </li>

                    </ul>
                </div>
            </nav>
            @*Content Area Srart Here*@
        <main class="content">
            <div class="container-fluid p-0">
                @RenderBody()
            </div>
            
        </main>
            @*Footer Section Start*@


            <div class="footer-basic">
                <footer>
                    <div class="social"><a href="mailto:shlomiref1991@gmail.com"><ion-icon name="mail"></ion-icon></a><a href="https://maps.google.com/?q=31.668982891638006, 34.57412589836485" target="_blank"><ion-icon name="map"></ion-icon></a><a href="tel:972503892656"><ion-icon name="call"></ion-icon></a><a href="https://wa.me/972503892656"><ion-icon name="logo-whatsapp"></ion-icon></a></div>
                    <ul class="list-inline">

                        <li class="list-inline-item"><a href="#">קצת עלינו</a></li>
                        <li class="list-inline-item"><a href="@Url.Action("Index", "ManageAccount")">דף הבית</a></li>
                    </ul>
                    <p class="copyright">פרויקט גמר © 2023</p>
                </footer>
            </div>


        </div>
    </div>
    @RenderSection("scripts", false)
    <script src="~/Content/JS/bootstrap.js"></script>
    <script src="~/Content/JS/app.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>

</body>
</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Responsive Admin &amp; Dashboard Template based on Bootstrap 5">
    <meta name="author" content="AdminKit">
    <meta name="keywords" content="adminkit, bootstrap, bootstrap 5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">
    <title>@ViewBag.Title - Vaccine App</title>
    <link href="~/Content/CSS/bootstrap.css" rel="stylesheet" />
    <link href="~/Fontawesome/css/all.css" rel="stylesheet" />
    <link href="~/Content/CSS/app.css" rel="stylesheet" />
    @RenderSection("Head", false)
</head>

<body>
        
    <div class="wrapper">
        @*Sidebar Navegation Start Here*@
        <nav id="sidebar" class="sidebar js-sidebar">
            <div class="sidebar-content js-simplebar">
                <a class="sidebar-brand" href="@Url.Action("IndexOfTherapist", "ManageAccount")">
                    <span class="align-middle">מערכת מעקב חיסונים</span>
                </a>

                <ul class="sidebar-nav">

                    <li class="sidebar-item active">
                        <a class="sidebar-link fs-4" href="@Url.Action("GetPatient", "ManageAccount")">
                            <i class="fa-solid fa-hospital-user"></i><span class="align-middle">מטופלים</span>
                        </a>
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link fs-4" href="@Url.Action("GetVaccination", "ManageAccount")">
                            <i class="fa-solid fa-syringe"></i><span class="align-middle">דיווח חיסון</span>

                        </a>
                    </li>

                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                    <li class="sidebar-item">
                        <a class="sidebar-link fs-4" href="@Url.Action("ChangePassword", "ManageAccount")">
                            <i class="fa-solid fa-lock"></i><span class="align-middle">שנה סיסמא</span>
                        </a>
                    </li>

                </ul>
            </div>
        </nav>

        <div class="main">
            <nav class="navbar navbar-expand navbar-light navbar-bg">
                <a class="sidebar-toggle js-sidebar-toggle">
                    <i class="hamburger align-self-center"></i>
                </a>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav navbar-align">
                        @*Top Navegation Start Here*@

                        <li class="nav-item dropdown">

                            <a class="nav-link d-none d-sm-inline-block fs-4" href="#" data-bs-toggle="dropdown">
                                <i class="fa-duotone fa-hands-clapping"></i>&nbsp;<span>שלום!&nbsp;@Session["username"]</span>
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link d-none d-sm-inline-block fs-4" href="/ManageAccount/Profile/@Session["id"]">
                                <i class="fa-solid fa-user"></i>
                            </a>
                        </li>
                        @*<li class="nav-item">
            <a class=" d-inline-block d-sm-none nav-link fs-4" href="#">
                <i class="fa-duotone fa-solid"></i>&nbsp;<span>Change Password&nbsp;@Session["username"]</span>
            </a>
        </li>*@
                        <li class="nav-item">
                            <a class="nav-link d-none d-sm-inline-block fs-4" href="@Url.Action("LogOff", "Account")">
                                <i class="fa-regular fa-arrow-up-left-from-circle"></i>
                            </a>
                        </li>
                        <img src="~/Image/Free_Sample_By_Wix.jpg" style="height:45px; width:45px" /> &nbsp;

                    </ul>
                </div>
            </nav>
            @*Content Area Srart Here*@
            <main class="content">
                <div class="container-fluid p-0">
                    @RenderBody()
                </div>


            </main>
            @*Footer Section Start*@
            <div class="footer-basic">
                <footer>
                    <div class="social"><a href="mailto:shlomiref1991@gmail.com"><ion-icon name="mail"></ion-icon></a><a href="https://maps.google.com/?q=31.668982891638006, 34.57412589836485" target="_blank"><ion-icon name="map"></ion-icon></a><a href="tel:972503892656"><ion-icon name="call"></ion-icon></a><a href="https://wa.me/972503892656"><ion-icon name="logo-whatsapp"></ion-icon></a></div>
                    <ul class="list-inline">

                        <li class="list-inline-item"><a href="#">קצת עלינו</a></li>
                        <li class="list-inline-item"><a href="@Url.Action("Index", "ManageAccount")">דף הבית</a></li>
                    </ul>
                    <p class="copyright">פרויקט גמר © 2023</p>
                </footer>
            </div>
        </div>
    </div>
    @RenderSection("scripts", false)
    <script src="~/Content/JS/bootstrap.js"></script>
    <script src="~/Content/JS/app.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>
</html>

Views/Shared/_Layout3.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
   
    <link href="~/Content/CSS/Layout3.css" rel="stylesheet" />
 
</head>

<body>
    <div class="topnav" id="myTopnav">
    <div class="dropdown">
        <button class="dropbtn">
            Dropdown
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            <a href="#">Link 1</a>
            <a href="#">Link 2</a>
            <a href="#">Link 3</a>
        </div>
    </div>
    <a href="#about">About</a>
    <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
    </div>

    <div style="padding-left:16px">
        <h2>Responsive Topnav with Dropdown</h2>
        <p>Resize the browser window to see how it works.</p>
        <p>Hover over the dropdown button to open the dropdown menu.</p>
    </div>
    <script src="~/Content/JS/Layout3.js"></script>
</body>
</html>

Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - מערכת בקרת התחסנות לאומית</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="~/Content/toastr.css" rel="stylesheet" />
</head>
<body>

    

        <div class="container body-content col-md-3">
            @RenderBody()


        </div>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
        <script src="~/Scripts/toastr.js"></script>
        @RenderSection("scripts", required: false)
    </body>
</html>

Views/Shared/_PatientNotFound.cshtml
<div class="row">
    <div class="col-8 mb-2">
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>The patient you are trying to book appointment for Does not exits!</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
</div>

Views/Shared/_Success.cshtml
<div class="row">
    <div class="col-8 mb-2">
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Operation Performed</strong> Data Inserted Successfually!!
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
</div>

Views/Shared/_fail.cshtml
<div class="row">
    <div class="col-8 mb-2">
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Therapist Does not exits!</strong> 
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
</div>